### ISSUE TITLE
Implement LLVM as an MLIR dialect

### ISSUE THREAD

**Issue by bollu** [opencompl/lean-mlir-old#3]
As we can now express MLIR, we should implement an interface for MLIR's LLVM dialect. This allows LEAN to interact and lower to LLVM in a _pure_ fashion, with no LLVM library dependency, if all one wants to do is to emit LLVM. This is modeled after [`llvm-hs-pure`](https://hackage.haskell.org/package/llvm-hs-pure)

**Comment by tobiasgrosser** [comment]
Nice!

**Comment by sunny-g** [comment]
Was this implemented somewhere?

**Comment by bollu** [comment]
This is being implemented within Lean itself, and will be upstreamed once stabilized:  https://github.com/bollu/lean4/blob/llvm/hargonix-collab/src/Lean/Compiler/IR/LLVM/Pure.lean
