### ISSUE TITLE
Get rid of stale branches `match-matcher` and `linalg-semantics`

### ISSUE THREAD

**Issue by lephe** [opencompl/lean-mlir-old#31]
These two branches are probably irrelevant now:

* The changes on `match-matcher` should already be in `rewriter` which is planned for merging in the future.
* The changes on `linalg-semantics` should already be in `linalg-theorems` which is the next big branch to merge.

@bollu @math-fehr could you check these and delete them if they're indeed irrelevant?

**Comment by math-fehr** [comment]
Done for `match-matcher`
